
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Sep 18 15:09:19 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int CONST = 7;
  public static final int ASSIGNMENT = 32;
  public static final int CASE = 18;
  public static final int NOT_EQUAL = 25;
  public static final int LPAREN = 38;
  public static final int GREATER = 26;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 46;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 39;
  public static final int SEMICOLON = 35;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int COMMA = 36;
  public static final int CLASS = 4;
  public static final int INC = 33;
  public static final int DIV = 22;
  public static final int LESS_EQUAL = 29;
  public static final int PLUS = 19;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 24;
  public static final int GREATER_EQUAL = 27;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 21;
  public static final int MOD = 23;
  public static final int IDENT = 45;
  public static final int FULL_STOP = 37;
  public static final int BREAK = 3;
  public static final int VOID = 16;
  public static final int SWITCH = 9;
  public static final int COLON = 44;
  public static final int LBRACE = 42;
  public static final int ELSE = 6;
  public static final int LSQUARE = 40;
  public static final int ENUM = 5;
  public static final int READ = 14;
  public static final int RSQUARE = 41;
  public static final int WHILE = 11;
  public static final int RBRACE = 43;
  public static final int BOOL_CONST = 48;
  public static final int DEC = 34;
  public static final int PRINT = 13;
  public static final int DO = 10;
}

