
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Sep 13 22:48:31 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 22;
  public static final int CONST = 7;
  public static final int ASSIGNMENT = 37;
  public static final int CASE = 19;
  public static final int NOT_EQUAL = 30;
  public static final int LPAREN = 43;
  public static final int GREATER = 31;
  public static final int CONTINUE = 18;
  public static final int NUM_CONST = 21;
  public static final int MINUS = 25;
  public static final int RPAREN = 44;
  public static final int SEMICOLON = 40;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 38;
  public static final int DIV = 27;
  public static final int QUESTION_MARK = 49;
  public static final int LESSER = 33;
  public static final int PLUS = 24;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 29;
  public static final int GREATER_EQUAL = 32;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int MOD = 28;
  public static final int FULL_STOP = 42;
  public static final int BREAK = 3;
  public static final int IDENT = 20;
  public static final int VOID = 16;
  public static final int SWITCH = 9;
  public static final int COLON = 50;
  public static final int LBRACE = 47;
  public static final int ELSE = 6;
  public static final int LSQUARE = 45;
  public static final int ENUM = 5;
  public static final int READ = 14;
  public static final int RSQUARE = 46;
  public static final int WHILE = 11;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 17;
  public static final int LESSER_EQUAL = 34;
  public static final int BOOL_CONST = 23;
  public static final int DEC = 39;
  public static final int PRINT = 13;
  public static final int DO = 10;
}

